### ISSUE TITLE
Recommended way to get the site header and footer

### ISSUE THREAD

**Issue by bilogic** [swiftmade/blogdown#19]
Hi,

Great package! It was really easy to get it installed and running. 

Do you guys have a recommended way to display/inherit the site's header and footer?

Thank you.

**Comment by aozisik** [comment]
Hi @bilogic,

The package ships with default views to render all blog posts, and a single post.

You can publish the view files:

```
php artisan vendor:publish  --provider "Swiftmade\Blogdown\BlogdownProvider"
```

and just get rid of all the extra header / footer tags. Since this is Laravel blade, you can use the `@extend`, or `@include` features to use your application's own layout.

https://laravel.com/docs/8.x/blade#extending-a-layout

Sorry for the late reply. Do let us know if you have other feedback about the package:)
